/* FILE NAME: TIMER.H
 * PROGRAMMER: SK3
 * DATE: 23.01.2019
 * PURPOSE: TIMER DECLARATION
 */

#ifndef __TIMER_H_
#define __TIMER_H_

#include "def.h"

/* Start measure function.
 * ARGUMENTS: None;
 * RETURNS: None.
 */
VOID SK3_TimerInit( VOID );

/* Response measure function.
 * ARGUMENTS: None;
 * RETURNS: None.
 */
VOID SK3_TimerResponse( VOID );

#endif /* __TIMER_H_ */

/* END OF 'TIMER.H' FILE */
